version: 2

models:
  - name: TEST_CREATE_ENVIRONMENT
    data_tests:
      - dbt_utils.expression_is_true:
          expression: "CONTAINS(UPPER(result), UPPER(validate_env_db_creation))"      
      - dbt_utils.expression_is_true:
          expression: "CONTAINS(UPPER(result), UPPER(validate_env_RW_role_creation))"      
      - dbt_utils.expression_is_true:
          expression: "CONTAINS(UPPER(result), UPPER(validate_env_RO_role_creation))"      
      - dbt_utils.expression_is_true:
          expression: "CONTAINS(UPPER(result), UPPER(validate_single_WH))"      
      - dbt_utils.expression_is_true:
          expression: "CONTAINS(UPPER(result), UPPER(validate_owner_role))"      
      - dbt_utils.expression_is_true:
          expression: "CONTAINS(UPPER(result), UPPER(validate_creator_role))"      
      - dbt_utils.expression_is_true:
          expression: "CONTAINS(UPPER(result), UPPER(validate_useradmin_role))"      
      - dbt_utils.expression_is_true:
          expression: "CONTAINS(UPPER(result), UPPER(validate_future_grants))"      
